# Uncomment the next line to define a global platform for your project
 platform :ios, '12.0'

target 'Map' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'SwiftLint'

  target 'MapTests' do
    inherit! :search_paths

    pod 'Quick'
    pod 'Nimble'
  end

  target 'MapUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
